---

- name: Gather facts
  action: amazon.aws.ec2_metadata_facts
  ignore_errors: yes 

- debug:
    msg: "{{ansible_ec2_public_ipv4}}"
  when: ansible_ec2_instance_type == "t1.micro"

- name: Ensure `listen` and `listen_ipv6` are mutually exclusive
  assert:
    that: "vsftpd_listen != vsftpd_listen_ipv6"


- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: Install vsftpd Packages
  package:
    name: '{{ vsftpd_packages }}'
    state: present

- name: Install Firewalld
  package:
    name: '{{ firewalld_packages }}'
    state: present
  when: ansible_os_family=="RedHat"

- name: Start Firewalld
  systemd:
    daemon-reload: yes
    state: restarted
    name: firewalld
  when: ansible_os_family == "RedHat"

- name: Add port to firewalld
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  loop:
    - 20-21/tcp
    - 1024-1048/tcp
  when: ansible_os_family == "RedHat"



- include_tasks: selinux.yml
  when: ansible_selinux is defined and ansible_selinux != false and ansible_selinux.status == 'enabled'

- name: Ensure `anon_root` exists
  file:
    path: '{{ vsftpd_anon_root }}'
    state: directory
    owner: '{{ vsftpd_owner }}'
    group: '{{ vsftpd_group }}'
    mode: '{{ vsftpd_mode }}'
    setype: '{{ vsftpd_setype }}'
  when: vsftpd_anon_root is defined

#- name: fix
#  shell: chmod g+s /var/ftp/pub/upload

- name: Creating directory
  file:
    path: '{{ vsftpd_anon_root }}/upload'
    state: directory
    owner: '{{ vsftpd_owner }}'
    group: '{{ vsftpd_group }}'
    mode: '{{ vsftpd_upload_mode }}'
  ignore_errors: yes  

- name: fix chown 
  shell: chown -R ftp:ftp /var/ftp/pub/
  when: ansible_os_family == "RedHat"

- name: fix chown 
  shell: chown -R ftp:ftp /var/ftp/pub/
  when: ansible_os_family == "Debian"


- name: fix chmod
  shell: chmod 0777 /var/ftp/pub/upload

- name: Ensure `local_root` exists
  file:
    path: '{{ vsftpd_local_root }}'
    state: directory
    owner: '{{ vsftpd_owner }}'
    group: '{{ vsftpd_group }}'
    mode: '{{ vsftpd_mode }}'
    setype: '{{ vsftpd_setype }}'
  when: vsftpd_local_root is defined


- name: Install configuration file
  template:
    src:  vsftpd.conf.j2
    dest: "{{ vsftpd_config_file }}"
    mode: '0600'

  notify: restart vsftpd


- name: Add extra permissions
  acl:
    name: "{{ item.folder }}"
    entity: "{{ item.entity }}"
    setype: "{{ item.setype }}"
    permissions: "{{ item.permissions }}"
    state: present
  with_items: "{{ vsftpd_extra_permissions }}"
  when: vsftpd_extra_permissions is defined

- name: Ensure service is started
  service:
    name: '{{ vsftpd_service }}'
    state: started
    enabled: YES

