---

- name: Allow full read/write access through SELinux for el7+
  seboolean:
    name: ftpd_full_access
    state: yes
    persistent: yes

# when:
#  - ansible_os_family == 'RedHat'
#  - ansible_distribution_major_version >= "7"

- name: Allow full read/write access through SELinux for el6
  seboolean:
    name: allow_ftpd_full_access
    state: yes
    persistent: yes

  when:
   - ansible_os_family == 'RedHat'
   - ansible_distribution_major_version == "6"

- name: Check if ftp_home_dir exists
  shell: getsebool -a | grep '^ftp_home_dir\b'
  register: var_exists
  failed_when: false
  changed_when: false


- name: Allow access to home directories
  seboolean:
    name: ftp_home_dir
    state: yes
    persistent: yes
  when: var_exists.rc == 0

